### PR TITLE
Corrected the Typographical errors

### PR DESCRIPTION
**Pull request by barath99**
Review the changes and merge with the master.

### CODE REVIEW

**Comment by jaxxstar** [comment]
@barath99  There are a few more typos in Readme.md
Correct those and then I'll merge the PR.

**Comment by barath99** [comment]
Can you check if it is alright now? I hope everything is done.

**Comment by jaxxstar** [comment]
@barath99 there are few more errors in findings.md, thanks for your help. There are a few outdated projects in spider-org. Outdated projects will be completely refactored, one by one. It is better to focus on refining active projects. We are ideating new projects this year, you are welcome to pitch in your ideas.

**Comment by barath99** [comment]
Alright! Closing the pr now. Looking forward to contribute towards new projects.

**Pull request closed without merging**
